### ISSUE TITLE
Localization/I18n support

### ISSUE THREAD

**Issue by sabriunal** [mibi88/MibiMdEditor#6]
Hi, would you like to add i18n support to your app. I'd like to translate it into my language.

Thanks.

**Comment by mibi88** [comment]
I just answered you at your PR. I'm adding it. I will translate it in French and German, but for other languages, help is welcome.

**Comment by mibi88** [comment]
I just finished it, now just translate it and I'll merge it!
I'll be very happy to see someone contributing on this project, thanks!

**Comment by mibi88** [comment]
But yes, currently not everything can be translated, I'll need to fix that before.

**Comment by sabriunal** [comment]
Would you check my findings ?

https://github.com/mibi88/MibiMdEditor/pull/8/files

**Comment by mibi88** [comment]
I saw them, I'll finish making it fully translatable this evening.
